-- Table: "extract".rr_data_definition

CREATE TABLE "extract".rr_data_definition
(
  upload_key character varying(5),
  "TABLE_NAME" character varying(30) NOT NULL,
  field_name character varying(30) NOT NULL,
  code_id character varying(10),
  mandatory numeric(1,0),
  "TYPE" character varying(1),
  alt_constraint character varying(30),
  alt_desc character varying(30),
  extra_val character varying(1),
  error_type integer,
  paed_mand numeric(1,0),
  ckd5_mand numeric(1,0),
  dependant_field character varying(30),
  alt_validation character varying(30),
  file_prefix character varying(20),
  load_min numeric(38,4),
  load_max numeric(38,4),
  remove_min numeric(38,4),
  remove_max numeric(38,4),
  in_month numeric(1,0),
  aki_mand numeric(1,0),
  rrt_mand numeric(1,0),
  cons_mand numeric(1,0),
  ckd4_mand numeric(1,0),
  valid_before_dob numeric(1,0),
  valid_after_dod numeric(1,0),
  in_quarter numeric(1,0)
)
WITH (
  OIDS=FALSE
);

ALTER TABLE "extract".rr_data_definition
  OWNER TO ukrdc;
GRANT ALL PRIVILEGES ON TABLE "extract".rr_data_definition TO ukrdc;