\i ../views/vwe_facility_relationship.SQL
\i ../views/vwe_satellite_map.SQL
\i ../views/vwe_pkb_members.SQL
\i ../views/vwe_pkb_test_patients.SQL
\i ../views/vwe_pv_members.SQL
\i ../views/vwe_result_types.SQL
\i ../views/vwe_extract_radar.SQL
\i ../views/vwe_extract_pkb_deceased.SQL
\i ../views/vwe_extract_pkb_deceased_test.SQL
\i ../views/vwe_extract_pkb_new.SQL
\i ../views/vwe_extract_pkb_new_test.SQL
\i ../views/vwe_extract_pkb_updates.SQL
\i ../views/vwe_extract_pv_pvxml.SQL
\i ../views/vwe_extract_pv_pvxml_eligable.SQL
\i ../views/vwe_extract_pv_pvxml_members.SQL
\i ../views/vwe_extract_pv_rda.SQL
\i ../views/vwe_survey_data.SQL

